(uiop:define-package #:dunge.crawler
  (:use #:cl #:dunge)
  (:shadowing-import-from #:dunge
                          #:room
                          #:sequence)
  (:import-from #:dunge
                #:*validate-room-targets*
                #:+dunge-rng-modulus+
                #:check-value
                #:format-dunge-value
                #:non-negative-integer
                #:positive-integer
                #:proper-list
                #:property-list)
  (:export
   #:build-game
   #:build-game-object
   #:build-resolve
   #:build-roll-dice
   #:build-roll-table
   #:build-world
   #:create-generated-room
   #:link-rooms
   #:room-plan-exit
   #:room-plan-exits
   #:room-plan-form
   #:room-plan-id
   #:room-plan-results
   #:set-initial-global
   #:set-player
   #:set-room-plan-exit
   #:encounter-entity-form
   #:encounter-spec
   #:inventory-entry-count
   #:inventory-entry-id
   #:inventory-entry-kind
   #:inventory-entry-slots
   #:item-catalog
   #:loot-choice-form
   #:player-declarations
   #:ration-choice-form
   #:resolve-table-result-data
   #:table-loot-entries
   #:table-result-encounters
   #:table-result-exits
   #:table-result-kind
   #:table-result-loot-p
   #:table-result-loot-results
   #:used-slots-expression
   #:+inventory-capacity+))
