;;; Golden console frames for the adaptation example. See tests/runtime-parity.lisp.

((:victory-loot-and-deeper-room
  ((:title "Dunge Crawler Testbed" :text
    ("A low campfire burns at the edge of the white arch. This is a tiny adaptation slice: authored rooms hand off to a generated dungeon graph prepared by Common Lisp."
     "The test delver has a lantern, two rations, and just enough nerve to step through.")
    :choices ("Approach the white arch" "Leave the testbed"))
   (:title "The White Arch" :text
    ("The arch is smooth, pale, and cold. The dungeon beyond it is generated by Common Lisp from Dunge-authored tables in the adaptation helper."
     "The first generated chamber waits in the run log. The CL adaptation helper can recall that same persistent room from here.")
    :choices ("Enter the generated chamber" "Return to camp"))
   (:title "White Arch" :text
    ("The white arch repeats itself in the dark, its stone too smooth to be old. A first find waits here: Chalk. A possible encounter stirs nearby: Watchful Shadow."
     "Room Segment: White Arch." "Find: Chalk." "Sign: Watchful Shadow stirs here."
     "Passage: Back." "Encounter: Watchful Shadow (active, HP 2/2).")
    :choices ("Attack watchful shadow" "Flee"))
   (:title "White Arch" :text
    ("You strike for 3 damage. Watchful Shadow falls."
     "The white arch repeats itself in the dark, its stone too smooth to be old. A first find waits here: Chalk. A possible encounter stirs nearby: Watchful Shadow."
     "Room Segment: White Arch." "Find: Chalk." "Sign: Watchful Shadow stirs here."
     "Passage: Back." "Encounter: Watchful Shadow (defeated, HP 0/2).")
    :choices ("Take chalk" "Return" "Continue deeper"))
   (:title "White Arch" :text
    ("You take chalk."
     "The white arch repeats itself in the dark, its stone too smooth to be old. A first find waits here: Chalk. A possible encounter stirs nearby: Watchful Shadow."
     "Room Segment: White Arch." "Find: Chalk." "Sign: Watchful Shadow stirs here."
     "Passage: Back." "Encounter: Watchful Shadow (defeated, HP 0/2).")
    :choices ("Return" "Continue deeper"))
   (:title "Cold Gallery" :text
    ("A cold gallery stretches ahead, with every footstep returning a little late. A find waits here: Ration. A possible encounter stirs nearby: Watchful Shadow. This chamber sits at depth 2."
     "Room Segment: Cold Gallery." "Find: Ration." "Sign: Watchful Shadow stirs here."
     "Encounter: Watchful Shadow (active, HP 2/2).")
    :choices ("Attack watchful shadow" "Flee"))
   (:title "Cold Gallery" :text
    ("You strike for 4 damage. Watchful Shadow falls."
     "A cold gallery stretches ahead, with every footstep returning a little late. A find waits here: Ration. A possible encounter stirs nearby: Watchful Shadow. This chamber sits at depth 2."
     "Room Segment: Cold Gallery." "Find: Ration." "Sign: Watchful Shadow stirs here."
     "Encounter: Watchful Shadow (defeated, HP 0/2).")
    :choices ("Take ration" "Return"))
   (:title "Cold Gallery" :text
    ("You take ration."
     "A cold gallery stretches ahead, with every footstep returning a little late. A find waits here: Ration. A possible encounter stirs nearby: Watchful Shadow. This chamber sits at depth 2."
     "Room Segment: Cold Gallery." "Find: Ration." "Sign: Watchful Shadow stirs here."
     "Encounter: Watchful Shadow (defeated, HP 0/2).")
    :choices ("Return"))
   (:title "White Arch" :text
    ("The white arch repeats itself in the dark, its stone too smooth to be old. A first find waits here: Chalk. A possible encounter stirs nearby: Watchful Shadow."
     "Room Segment: White Arch." "Find: Chalk." "Sign: Watchful Shadow stirs here."
     "Passage: Back." "Encounter: Watchful Shadow (defeated, HP 0/2).")
    :choices ("Return" "Continue deeper"))
   (:title "The White Arch" :text
    ("The arch is smooth, pale, and cold. The dungeon beyond it is generated by Common Lisp from Dunge-authored tables in the adaptation helper."
     "The first generated chamber waits in the run log. The CL adaptation helper can recall that same persistent room from here.")
    :choices ("Enter the generated chamber" "Return to camp"))
   (:title "White Arch" :text
    ("The white arch repeats itself in the dark, its stone too smooth to be old. A first find waits here: Chalk. A possible encounter stirs nearby: Watchful Shadow."
     "Room Segment: White Arch." "Find: Chalk." "Sign: Watchful Shadow stirs here."
     "Passage: Back." "Encounter: Watchful Shadow (defeated, HP 0/2).")
    :choices ("Return" "Continue deeper"))))
 (:wounded-eats-ration-mid-fight
  ((:title "Dunge Crawler Testbed" :text
    ("A low campfire burns at the edge of the white arch. This is a tiny adaptation slice: authored rooms hand off to a generated dungeon graph prepared by Common Lisp."
     "The test delver has a lantern, two rations, and just enough nerve to step through.")
    :choices ("Approach the white arch" "Leave the testbed"))
   (:title "The White Arch" :text
    ("The arch is smooth, pale, and cold. The dungeon beyond it is generated by Common Lisp from Dunge-authored tables in the adaptation helper."
     "The first generated chamber waits in the run log. The CL adaptation helper can recall that same persistent room from here.")
    :choices ("Enter the generated chamber" "Return to camp"))
   (:title "White Arch" :text
    ("The white arch repeats itself in the dark, its stone too smooth to be old. A first find waits here: 5 gold. A possible encounter stirs nearby: Watchful Shadow."
     "Room Segment: White Arch." "Treasure: 5 gold." "Sign: Watchful Shadow stirs here."
     "Passage: Back." "Encounter: Watchful Shadow (active, HP 2/2).")
    :choices ("Attack watchful shadow" "Flee"))
   (:title "White Arch" :text
    ("You strike for 1 damage. Watchful Shadow hits back for 1 damage."
     "The white arch repeats itself in the dark, its stone too smooth to be old. A first find waits here: 5 gold. A possible encounter stirs nearby: Watchful Shadow."
     "Room Segment: White Arch." "Treasure: 5 gold." "Sign: Watchful Shadow stirs here."
     "Passage: Back." "Encounter: Watchful Shadow (active, HP 1/2).")
    :choices ("Attack watchful shadow" "Eat ration" "Flee"))
   (:title "White Arch" :text
    ("You eat a ration and recover."
     "The white arch repeats itself in the dark, its stone too smooth to be old. A first find waits here: 5 gold. A possible encounter stirs nearby: Watchful Shadow."
     "Room Segment: White Arch." "Treasure: 5 gold." "Sign: Watchful Shadow stirs here."
     "Passage: Back." "Encounter: Watchful Shadow (active, HP 1/2).")
    :choices ("Attack watchful shadow" "Flee"))
   (:title "White Arch" :text
    ("You strike for 4 damage. Watchful Shadow falls."
     "The white arch repeats itself in the dark, its stone too smooth to be old. A first find waits here: 5 gold. A possible encounter stirs nearby: Watchful Shadow."
     "Room Segment: White Arch." "Treasure: 5 gold." "Sign: Watchful Shadow stirs here."
     "Passage: Back." "Encounter: Watchful Shadow (defeated, HP 0/2).")
    :choices ("Take 5 gold" "Return" "Continue deeper"))
   (:title "White Arch" :text
    ("You take 5 gold."
     "The white arch repeats itself in the dark, its stone too smooth to be old. A first find waits here: 5 gold. A possible encounter stirs nearby: Watchful Shadow."
     "Room Segment: White Arch." "Treasure: 5 gold." "Sign: Watchful Shadow stirs here."
     "Passage: Back." "Encounter: Watchful Shadow (defeated, HP 0/2).")
    :choices ("Return" "Continue deeper"))
   (:title "The White Arch" :text
    ("The arch is smooth, pale, and cold. The dungeon beyond it is generated by Common Lisp from Dunge-authored tables in the adaptation helper."
     "The first generated chamber waits in the run log. The CL adaptation helper can recall that same persistent room from here.")
    :choices ("Enter the generated chamber" "Return to camp"))
   (:title "White Arch" :text
    ("The white arch repeats itself in the dark, its stone too smooth to be old. A first find waits here: 5 gold. A possible encounter stirs nearby: Watchful Shadow."
     "Room Segment: White Arch." "Treasure: 5 gold." "Sign: Watchful Shadow stirs here."
     "Passage: Back." "Encounter: Watchful Shadow (defeated, HP 0/2).")
    :choices ("Return" "Continue deeper"))))
 (:flee-then-loot
  ((:title "Dunge Crawler Testbed" :text
    ("A low campfire burns at the edge of the white arch. This is a tiny adaptation slice: authored rooms hand off to a generated dungeon graph prepared by Common Lisp."
     "The test delver has a lantern, two rations, and just enough nerve to step through.")
    :choices ("Approach the white arch" "Leave the testbed"))
   (:title "The White Arch" :text
    ("The arch is smooth, pale, and cold. The dungeon beyond it is generated by Common Lisp from Dunge-authored tables in the adaptation helper."
     "The first generated chamber waits in the run log. The CL adaptation helper can recall that same persistent room from here.")
    :choices ("Enter the generated chamber" "Return to camp"))
   (:title "White Arch" :text
    ("The white arch repeats itself in the dark, its stone too smooth to be old. A first find waits here: Ration. A possible encounter stirs nearby: Watchful Shadow."
     "Room Segment: White Arch." "Find: Ration." "Sign: Watchful Shadow stirs here."
     "Passage: Back." "Encounter: Watchful Shadow (active, HP 2/2).")
    :choices ("Attack watchful shadow" "Flee"))
   (:title "White Arch" :text
    ("You escape from Watchful Shadow."
     "The white arch repeats itself in the dark, its stone too smooth to be old. A first find waits here: Ration. A possible encounter stirs nearby: Watchful Shadow."
     "Room Segment: White Arch." "Find: Ration." "Sign: Watchful Shadow stirs here."
     "Passage: Back." "Encounter: Watchful Shadow (escaped, HP 2/2).")
    :choices ("Take ration" "Return" "Continue deeper"))
   (:title "White Arch" :text
    ("You take ration."
     "The white arch repeats itself in the dark, its stone too smooth to be old. A first find waits here: Ration. A possible encounter stirs nearby: Watchful Shadow."
     "Room Segment: White Arch." "Find: Ration." "Sign: Watchful Shadow stirs here."
     "Passage: Back." "Encounter: Watchful Shadow (escaped, HP 2/2).")
    :choices ("Return" "Continue deeper"))
   (:title "The White Arch" :text
    ("The arch is smooth, pale, and cold. The dungeon beyond it is generated by Common Lisp from Dunge-authored tables in the adaptation helper."
     "The first generated chamber waits in the run log. The CL adaptation helper can recall that same persistent room from here.")
    :choices ("Enter the generated chamber" "Return to camp"))
   (:title "White Arch" :text
    ("The white arch repeats itself in the dark, its stone too smooth to be old. A first find waits here: Ration. A possible encounter stirs nearby: Watchful Shadow."
     "Room Segment: White Arch." "Find: Ration." "Sign: Watchful Shadow stirs here."
     "Passage: Back." "Encounter: Watchful Shadow (escaped, HP 2/2).")
    :choices ("Return" "Continue deeper"))))
 (:gold-loot
  ((:title "Dunge Crawler Testbed" :text
    ("A low campfire burns at the edge of the white arch. This is a tiny adaptation slice: authored rooms hand off to a generated dungeon graph prepared by Common Lisp."
     "The test delver has a lantern, two rations, and just enough nerve to step through.")
    :choices ("Approach the white arch" "Leave the testbed"))
   (:title "The White Arch" :text
    ("The arch is smooth, pale, and cold. The dungeon beyond it is generated by Common Lisp from Dunge-authored tables in the adaptation helper."
     "The first generated chamber waits in the run log. The CL adaptation helper can recall that same persistent room from here.")
    :choices ("Enter the generated chamber" "Return to camp"))
   (:title "White Arch" :text
    ("The white arch repeats itself in the dark, its stone too smooth to be old. A first find waits here: 5 gold. A possible encounter stirs nearby: Watchful Shadow."
     "Room Segment: White Arch." "Treasure: 5 gold." "Sign: Watchful Shadow stirs here."
     "Passage: Back." "Encounter: Watchful Shadow (active, HP 2/2).")
    :choices ("Attack watchful shadow" "Flee"))
   (:title "White Arch" :text
    ("You strike for 5 damage. Watchful Shadow falls."
     "The white arch repeats itself in the dark, its stone too smooth to be old. A first find waits here: 5 gold. A possible encounter stirs nearby: Watchful Shadow."
     "Room Segment: White Arch." "Treasure: 5 gold." "Sign: Watchful Shadow stirs here."
     "Passage: Back." "Encounter: Watchful Shadow (defeated, HP 0/2).")
    :choices ("Take 5 gold" "Return" "Continue deeper"))
   (:title "White Arch" :text
    ("You take 5 gold."
     "The white arch repeats itself in the dark, its stone too smooth to be old. A first find waits here: 5 gold. A possible encounter stirs nearby: Watchful Shadow."
     "Room Segment: White Arch." "Treasure: 5 gold." "Sign: Watchful Shadow stirs here."
     "Passage: Back." "Encounter: Watchful Shadow (defeated, HP 0/2).")
    :choices ("Return" "Continue deeper"))
   (:title "The White Arch" :text
    ("The arch is smooth, pale, and cold. The dungeon beyond it is generated by Common Lisp from Dunge-authored tables in the adaptation helper."
     "The first generated chamber waits in the run log. The CL adaptation helper can recall that same persistent room from here.")
    :choices ("Enter the generated chamber" "Return to camp"))))
 (:delver-armor-absorbs-hit
  ((:title "Dunge Crawler Testbed" :text
    ("A low campfire burns at the edge of the white arch. This is a tiny adaptation slice: authored rooms hand off to a generated dungeon graph prepared by Common Lisp."
     "The test delver has a lantern, two rations, and just enough nerve to step through.")
    :choices ("Approach the white arch" "Leave the testbed"))
   (:title "The White Arch" :text
    ("The arch is smooth, pale, and cold. The dungeon beyond it is generated by Common Lisp from Dunge-authored tables in the adaptation helper."
     "The first generated chamber waits in the run log. The CL adaptation helper can recall that same persistent room from here.")
    :choices ("Enter the generated chamber" "Return to camp"))
   (:title "White Arch" :text
    ("The white arch repeats itself in the dark, its stone too smooth to be old. A first find waits here: 5 gold. A possible encounter stirs nearby: Watchful Shadow."
     "Room Segment: White Arch." "Treasure: 5 gold." "Sign: Watchful Shadow stirs here."
     "Passage: Back." "Encounter: Watchful Shadow (active, HP 2/2).")
    :choices ("Attack watchful shadow" "Flee"))
   (:title "White Arch" :text
    ("You strike for 1 damage. Watchful Shadow hits back for 0 damage."
     "The white arch repeats itself in the dark, its stone too smooth to be old. A first find waits here: 5 gold. A possible encounter stirs nearby: Watchful Shadow."
     "Room Segment: White Arch." "Treasure: 5 gold." "Sign: Watchful Shadow stirs here."
     "Passage: Back." "Encounter: Watchful Shadow (active, HP 1/2).")
    :choices ("Attack watchful shadow" "Flee"))
   (:title "White Arch" :text
    ("You strike for 4 damage. Watchful Shadow falls."
     "The white arch repeats itself in the dark, its stone too smooth to be old. A first find waits here: 5 gold. A possible encounter stirs nearby: Watchful Shadow."
     "Room Segment: White Arch." "Treasure: 5 gold." "Sign: Watchful Shadow stirs here."
     "Passage: Back." "Encounter: Watchful Shadow (defeated, HP 0/2).")
    :choices ("Take 5 gold" "Return" "Continue deeper"))
   (:title "White Arch" :text
    ("You take 5 gold."
     "The white arch repeats itself in the dark, its stone too smooth to be old. A first find waits here: 5 gold. A possible encounter stirs nearby: Watchful Shadow."
     "Room Segment: White Arch." "Treasure: 5 gold." "Sign: Watchful Shadow stirs here."
     "Passage: Back." "Encounter: Watchful Shadow (defeated, HP 0/2).")
    :choices ("Return" "Continue deeper"))
   (:title "The White Arch" :text
    ("The arch is smooth, pale, and cold. The dungeon beyond it is generated by Common Lisp from Dunge-authored tables in the adaptation helper."
     "The first generated chamber waits in the run log. The CL adaptation helper can recall that same persistent room from here.")
    :choices ("Enter the generated chamber" "Return to camp")))))
