
(uiop:define-package #:dunge
  (:use #:cl)
  (:mix #:trivia)
  (:shadow #:room
           #:sequence)
  (:export
   #:*input*
   #:*output*
   #:*pause-after-say*
   #:*debug*
   #:action
   #:action-owner
   #:back
   #:branch
   #:choice
   #:choice-condition
   #:choice-id
   #:choice-once-p
   #:choices
   #:close-choice
   #:condition-and
   #:condition-eq
   #:condition-not
   #:condition-or
   #:conditional-effect
   #:collect-choices
   #:compile-dunge-source
   #:container
   #:container-view
   #:capture-runtime-state
   #:dunge-source-error
   #:dunge-source-error-message
   #:contents
   #:describe-entity
   #:description
   #:enter
   #:enter-target
   #:entity
   #:entities
   #:evaluate-expression
   #:evaluate-condition
   #:evaluate
   #:evaluate-session
   #:execute-effect
   #:game
   #:game-global-state
   #:game-global-state-declarations
   #:game-player
   #:game-rooms
   #:game-start
   #:game-taken-choices
   #:gosub
   #:goto
   #:interaction-label
   #:interaction-target
   #:item
   #:label
   #:load-dunge-file
   #:load-dunge-string
   #:load-runtime-state-file
   #:make-runtime-session
   #:name
   #:node-children
   #:node-id
   #:open-choice
   #:options
   #:p
   #:placed-thing
   #:placement-description
   #:quit
   #:room
   #:room-title
   #:room-name
   #:read-runtime-state-file
   #:restore-runtime-state
   #:make-runtime-context
   #:runtime-context
   #:runtime-context-game
   #:runtime-context-scene
   #:runtime-context-self
   #:runtime-session
   #:runtime-session-current-room-name
   #:runtime-session-game
   #:runtime-session-location
   #:runtime-session-return-stack
   #:runtime-session-return-stack-room-names
   #:say
   #:sequence
   #:state-clear
   #:state-dec
   #:state-inc
   #:state-ref
   #:state-set
   #:state-toggle
   #:target
   #:text
   #:validate-game
   #:validate-node
   #:validate-room
   #:walk-node-tree
   #:viewed-container
   #:write-runtime-state-file))
