
(uiop:define-package #:dunge
  (:use #:cl)
  (:mix #:trivia)
  (:shadow #:room
           #:sequence)
  (:export
   #:*input*
   #:*output*
   #:*pause-after-say*
   #:*debug*
   #:+player-inventory-capacity+
   #:action
   #:action-owner
   #:back
   #:branch
   #:availability-condition
   #:availability-mixin
   #:available-p
   #:choice
   #:choice-condition
   #:choice-id
   #:choice-once-p
   #:choices
   #:close-choice
   #:condition-and
   #:condition-eq
   #:condition-not
   #:condition-or
   #:conditional-effect
   #:consumable-id
   #:consumable-mixin
   #:consumable-once-p
   #:consume-node
   #:consumed-p
   #:collect-choices
   #:compile-dunge-source
   #:container
   #:container-view
   #:capture-runtime-state
   #:dunge-source-error
   #:dunge-source-error-message
   #:contents
   #:describe-entity
   #:description
   #:enter
   #:enter-target
   #:entity
   #:entities
   #:evaluate-expression
   #:evaluate-condition
   #:evaluate
   #:evaluate-session
   #:execute-effect
   #:game
   #:game-encounter-index
   #:game-encounter-states
   #:game-global-state
   #:game-global-state-declarations
   #:game-generated-room-counter
   #:game-generated-rooms
   #:game-player
   #:game-random-seed
   #:game-random-state
   #:game-rooms
   #:game-roll-log
   #:game-start
   #:game-tables
   #:game-taken-choices
   #:find-player-inventory-entry
   #:find-generated-room
   #:find-encounter-state
   #:encounter-active-p
   #:encounter-armor
   #:encounter-damage
   #:encounter-enemy-id
   #:encounter-finished-p
   #:encounter-hp
   #:encounter-max-hp
   #:encounter-max-str
   #:encounter-reaction
   #:encounter-room-name
   #:encounter-round
   #:encounter-source
   #:encounter-state
   #:encounter-state-plist
   #:encounter-status
   #:encounter-str
   #:generated-room
   #:generated-room-description
   #:generated-room-depth
   #:generated-room-exits
   #:generated-room-exit-target
   #:generated-room-results
   #:generated-room-state-plist
   #:generated-room-visited-p
   #:generated-room-zone
   #:gosub
   #:goto
   #:add-player-inventory-entry
   #:apply-resolved-table-result-to-player
   #:apply-table-result-to-player
   #:interaction-label
   #:interaction-target
   #:inventory-entry-bulky-p
   #:inventory-entry-count
   #:inventory-entry-id
   #:inventory-entry-kind
   #:inventory-entry-slots
   #:inventory-entry-tags
   #:item
   #:label
   #:link-generated-rooms
   #:load-dunge-file
   #:load-dunge-string
   #:load-runtime-state-file
   #:make-runtime-session
   #:make-generated-room
   #:make-encounter-state
   #:name
   #:node-children
   #:node-id
   #:node-priority
   #:node-tags
   #:open-choice
   #:options
   #:p
   #:parse-dice-expression
   #:placed-thing
   #:placement-description
   #:player
   #:player-armor
   #:player-background
   #:player-conditions
   #:player-deprived-p
   #:player-dex
   #:player-fatigue
   #:player-fate
   #:player-gold
   #:player-hp
   #:player-inventory
   #:player-inventory-capacity
   #:player-inventory-count
   #:player-inventory-free-slots
   #:player-inventory-full-p
   #:player-inventory-used-slots
   #:player-max-dex
   #:player-max-hp
   #:player-max-str
   #:player-max-wil
   #:player-name
   #:player-str
   #:player-wil
   #:quit
   #:room
   #:room-title
   #:room-name
   #:read-runtime-state-file
   #:register-generated-room
   #:register-encounter-state
   #:remove-player-inventory-entry
   #:restore-runtime-state
   #:attack-encounter
   #:ensure-room-encounter-state
   #:flee-encounter
   #:make-runtime-context
   #:prioritized-mixin
   #:random-table
   #:runtime-context
   #:runtime-context-game
   #:runtime-context-scene
   #:runtime-context-self
   #:runtime-session
   #:runtime-session-current-room-name
   #:runtime-session-game
   #:runtime-session-location
   #:runtime-session-return-stack
   #:runtime-session-return-stack-room-names
   #:say
   #:sequence
   #:set-generated-room-exit
   #:state-clear
   #:state-dec
   #:state-inc
   #:state-ref
   #:state-set
   #:state-toggle
   #:tagged-mixin
   #:roll-dice
   #:roll-dice-value
   #:roll-table
   #:create-generated-room
   #:allocate-generated-room-id
   #:game-random
   #:table-entries
   #:table-entry
   #:table-entry-id
   #:table-entry-range
   #:table-entry-result
   #:table-entry-weight
   #:table-result-encounters
   #:table-result-exits
   #:table-id
   #:table-index
   #:table-mode
   #:resolve-table-result-data
   #:target
   #:text
   #:validate-game
   #:validate-node
   #:validate-room
   #:walk-node-tree
   #:viewed-container
   #:write-runtime-state-file))
