(uiop:define-package #:dunge.ast
  (:use)
  (:documentation "The AST protocol for backends: node classes and the readers
that expose their definitions. These are Dunge's own symbols, re-exported so a
backend such as the HTML compiler never needs internal symbols.")
  (:import-from #:dunge
                #:action
                #:action-owner
                #:back
                #:branch
                #:branch-condition
                #:branch-then-entities
                #:branch-else-entities
                #:choice
                #:choice-condition
                #:choice-id
                #:choice-once-p
                #:choices
                #:options
                #:open-choice
                #:close-choice
                #:arithmetic
                #:arithmetic-operator
                #:arithmetic-operands
                #:concat
                #:concat-parts
                #:condition-eq
                #:condition-compare
                #:comparison-operator
                #:condition-left
                #:condition-right
                #:condition-not
                #:condition-child
                #:condition-and
                #:condition-or
                #:conditions
                #:conditional-effect
                #:conditional-effect-condition
                #:conditional-effect-then
                #:conditional-effect-else
                #:container
                #:container-view
                #:viewed-container
                #:contents
                #:description
                #:enter
                #:enter-target
                #:entity
                #:entities
                #:entity-id
                #:entity-refs
                #:state-declarations
                #:effects
                #:gosub
                #:goto
                #:room-name
                #:interaction-label
                #:interaction-target
                #:item
                #:label
                #:p
                #:text
                #:placement
                #:placement-description
                #:quit
                #:refresh
                #:roll
                #:roll-spec
                #:roll-label
                #:say
                #:say-text
                #:sequence
                #:sequence-effects
                #:state-clear
                #:state-dec
                #:state-inc
                #:state-set
                #:state-toggle
                #:effect-target
                #:effect-value
                #:effect-amount
                #:state-ref
                #:state-ref-scope
                #:state-ref-role
                #:state-ref-key
                #:target
                #:node-id
                #:node-children
                #:+dunge-rng-modulus+
                #:+max-safe-integer+
                #:safe-integer-p
                #:game
                #:game-rooms
                #:game-start
                #:game-random-seed
                #:game-global-state-declarations
                #:game-player-state-declarations
                #:room
                #:room-title
                #:name
                #:validate-game)
  (:export
   #:action
   #:action-owner
   #:back
   #:branch
   #:branch-condition
   #:branch-then-entities
   #:branch-else-entities
   #:choice
   #:choice-condition
   #:choice-id
   #:choice-once-p
   #:choices
   #:options
   #:open-choice
   #:close-choice
   #:arithmetic
   #:arithmetic-operator
   #:arithmetic-operands
   #:concat
   #:concat-parts
   #:condition-eq
   #:condition-compare
   #:comparison-operator
   #:condition-left
   #:condition-right
   #:condition-not
   #:condition-child
   #:condition-and
   #:condition-or
   #:conditions
   #:conditional-effect
   #:conditional-effect-condition
   #:conditional-effect-then
   #:conditional-effect-else
   #:container
   #:container-view
   #:viewed-container
   #:contents
   #:description
   #:enter
   #:enter-target
   #:entity
   #:entities
   #:entity-id
   #:entity-refs
   #:state-declarations
   #:effects
   #:gosub
   #:goto
   #:room-name
   #:interaction-label
   #:interaction-target
   #:item
   #:label
   #:p
   #:text
   #:placement
   #:placement-description
   #:quit
   #:refresh
   #:roll
   #:roll-spec
   #:roll-label
   #:say
   #:say-text
   #:sequence
   #:sequence-effects
   #:state-clear
   #:state-dec
   #:state-inc
   #:state-set
   #:state-toggle
   #:effect-target
   #:effect-value
   #:effect-amount
   #:state-ref
   #:state-ref-scope
   #:state-ref-role
   #:state-ref-key
   #:target
   #:node-id
   #:node-children
   #:+dunge-rng-modulus+
   #:+max-safe-integer+
   #:safe-integer-p
   #:game
   #:game-rooms
   #:game-start
   #:game-random-seed
   #:game-global-state-declarations
   #:game-player-state-declarations
   #:room
   #:room-title
   #:name
   #:validate-game))
